<?php

/**
 * @return array
 */
function islandora_webform_profile_webform_component_info() {
  $components = [];
  $components['u'] = [
    'label' => t('Profile U1/U2'),
    'description' => t('Fields to link content to profiles'),
    'features' => [
      'csv' => TRUE,
      'email' => TRUE,
      'email_address' => FALSE,
      'email_name' => FALSE,
      'required' => FALSE,
      'title_display' => FALSE,
      'title_inline' => FALSE,
      'conditional' => FALSE,
      'group' => FALSE,
      'spam_analysis' => FALSE,
      'attachment' => FALSE,
      'private' => FALSE,
    ],
    'file' => 'components/u.inc',
  ];

  return $components;
}
